package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkflowException extends java.lang.RuntimeException {

	private final String message;

    public WorkflowException(String message) {
		super(message);
		this.message = message;
	}

	@Override
	public String toString() {
		return this.message;
	}

    @Override
	public java.lang.String getMessage() {
		return this.message;
	}
	
}