package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkflowItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long workflowItemId;

	private java.lang.String assignedTo;

	private java.lang.String action;

	private java.lang.String statusCode;

	private java.lang.Boolean defaultRule;

	private java.lang.String role;

	private Integer projectId;

	private java.lang.Long memberId;

	private java.lang.Long subMeasureGroupId;

	private java.lang.String visitSSUI;

	private java.util.Date denominatorInclusionDate;

	private java.lang.Long medicalRecordId;

	private java.lang.Long chaseItemId;

	private java.util.Date dueDate;

	private java.lang.String reviewBy;

	private java.util.Date reportingFromDate;

	private java.util.Date reportingToDate;

	private java.lang.Boolean activeFlag;

	private java.lang.Long processInstanceId;

	private java.lang.String workflowContainerId;

	private java.lang.Boolean workflowInProgress;

	private java.lang.Integer overreadCount;

	private java.util.Date assignedDate;

	private java.util.Date createdDate;

	private java.util.Date modifiedDate;

	private java.lang.String createdBy;

	private java.lang.String modifiedBy;

	private java.lang.Boolean deletedFlag;

	private java.lang.String projectType;

	private java.lang.String workflowItemCode;

	private java.lang.String businessGroupCode;

	private java.lang.String subMeasureGroupCode;

	private java.lang.String workflowIndicator;

	private java.lang.Boolean rtpFlag;

	private java.lang.Boolean holdFlag;

	private java.lang.Long workflowRequestId;

	private java.lang.String sectionIndicator;

	private java.lang.Boolean exceptionFlag;

	private java.lang.Boolean mandatoryReviewFlag;

	private java.lang.Long chaseStatusId;

	private java.lang.Boolean editFlag;

	private java.lang.Boolean hasMissingValue;

	private java.lang.Integer complianceStatus;

	public WorkflowItem() {
	}

	public java.lang.Long getWorkflowItemId() {
		return this.workflowItemId;
	}

	public void setWorkflowItemId(java.lang.Long workflowItemId) {
		this.workflowItemId = workflowItemId;
	}

	public java.lang.String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(java.lang.String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(java.lang.String statusCode) {
		this.statusCode = statusCode;
	}

	public java.lang.Boolean getDefaultRule() {
		return this.defaultRule;
	}

	public void setDefaultRule(java.lang.Boolean defaultRule) {
		this.defaultRule = defaultRule;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(java.lang.Long memberId) {
		this.memberId = memberId;
	}

	public java.lang.Long getSubMeasureGroupId() {
		return this.subMeasureGroupId;
	}

	public void setSubMeasureGroupId(java.lang.Long subMeasureGroupId) {
		this.subMeasureGroupId = subMeasureGroupId;
	}

	public java.lang.String getVisitSSUI() {
		return this.visitSSUI;
	}

	public void setVisitSSUI(java.lang.String visitSSUI) {
		this.visitSSUI = visitSSUI;
	}

	public java.util.Date getDenominatorInclusionDate() {
		return this.denominatorInclusionDate;
	}

	public void setDenominatorInclusionDate(
			java.util.Date denominatorInclusionDate) {
		this.denominatorInclusionDate = denominatorInclusionDate;
	}

	public java.lang.Long getMedicalRecordId() {
		return this.medicalRecordId;
	}

	public void setMedicalRecordId(java.lang.Long medicalRecordId) {
		this.medicalRecordId = medicalRecordId;
	}

	public java.lang.Long getChaseItemId() {
		return this.chaseItemId;
	}

	public void setChaseItemId(java.lang.Long chaseItemId) {
		this.chaseItemId = chaseItemId;
	}

	public java.util.Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.util.Date dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.String getReviewBy() {
		return this.reviewBy;
	}

	public void setReviewBy(java.lang.String reviewBy) {
		this.reviewBy = reviewBy;
	}

	public java.util.Date getReportingFromDate() {
		return this.reportingFromDate;
	}

	public void setReportingFromDate(java.util.Date reportingFromDate) {
		this.reportingFromDate = reportingFromDate;
	}

	public java.util.Date getReportingToDate() {
		return this.reportingToDate;
	}

	public void setReportingToDate(java.util.Date reportingToDate) {
		this.reportingToDate = reportingToDate;
	}

	public java.lang.Boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(java.lang.Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getWorkflowContainerId() {
		return this.workflowContainerId;
	}

	public void setWorkflowContainerId(java.lang.String workflowContainerId) {
		this.workflowContainerId = workflowContainerId;
	}

	public java.lang.Boolean getWorkflowInProgress() {
		return this.workflowInProgress;
	}

	public void setWorkflowInProgress(java.lang.Boolean workflowInProgress) {
		this.workflowInProgress = workflowInProgress;
	}

	public java.util.Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(java.util.Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.util.Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(java.util.Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
	}

	public java.lang.String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(java.lang.String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public java.lang.Boolean getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(java.lang.Boolean deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	public java.lang.String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(java.lang.String projectType) {
		this.projectType = projectType;
	}

	public java.lang.String getWorkflowItemCode() {
		return this.workflowItemCode;
	}

	public void setWorkflowItemCode(java.lang.String workflowItemCode) {
		this.workflowItemCode = workflowItemCode;
	}

	public java.lang.String getBusinessGroupCode() {
		return this.businessGroupCode;
	}

	public void setBusinessGroupCode(java.lang.String businessGroupCode) {
		this.businessGroupCode = businessGroupCode;
	}

	public java.lang.String getSubMeasureGroupCode() {
		return this.subMeasureGroupCode;
	}

	public void setSubMeasureGroupCode(java.lang.String subMeasureGroupCode) {
		this.subMeasureGroupCode = subMeasureGroupCode;
	}

	public java.lang.String getWorkflowIndicator() {
		return this.workflowIndicator;
	}

	public void setWorkflowIndicator(java.lang.String workflowIndicator) {
		this.workflowIndicator = workflowIndicator;
	}

	public java.lang.Boolean getRtpFlag() {
		return this.rtpFlag;
	}

	public void setRtpFlag(java.lang.Boolean rtpFlag) {
		this.rtpFlag = rtpFlag;
	}

	public java.lang.Boolean getHoldFlag() {
		return this.holdFlag;
	}

	public void setHoldFlag(java.lang.Boolean holdFlag) {
		this.holdFlag = holdFlag;
	}

	public java.lang.Long getWorkflowRequestId() {
		return this.workflowRequestId;
	}

	public void setWorkflowRequestId(java.lang.Long workflowRequestId) {
		this.workflowRequestId = workflowRequestId;
	}

	public java.lang.Integer getOverreadCount() {
		return this.overreadCount;
	}

	public void setOverreadCount(java.lang.Integer overreadCount) {
		this.overreadCount = overreadCount;
	}

	public java.lang.Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(java.lang.Integer projectId) {
		this.projectId = projectId;
	}

	public java.lang.String getSectionIndicator() {
		return this.sectionIndicator;
	}

	public void setSectionIndicator(java.lang.String sectionIndicator) {
		this.sectionIndicator = sectionIndicator;
	}

	public java.lang.Boolean getExceptionFlag() {
		return this.exceptionFlag;
	}

	public void setExceptionFlag(java.lang.Boolean exceptionFlag) {
		this.exceptionFlag = exceptionFlag;
	}

	public java.lang.Boolean getMandatoryReviewFlag() {
		return this.mandatoryReviewFlag;
	}

	public void setMandatoryReviewFlag(java.lang.Boolean mandatoryReviewFlag) {
		this.mandatoryReviewFlag = mandatoryReviewFlag;
	}

	public java.lang.Long getChaseStatusId() {
		return this.chaseStatusId;
	}

	public void setChaseStatusId(java.lang.Long chaseStatusId) {
		this.chaseStatusId = chaseStatusId;
	}

	public java.lang.Boolean getEditFlag() {
		return this.editFlag;
	}

	public void setEditFlag(java.lang.Boolean editFlag) {
		this.editFlag = editFlag;
	}

	public java.lang.Boolean getHasMissingValue() {
		return this.hasMissingValue;
	}

	public void setHasMissingValue(java.lang.Boolean hasMissingValue) {
		this.hasMissingValue = hasMissingValue;
	}

	public java.lang.Integer getComplianceStatus() {
		return this.complianceStatus;
	}

	public void setComplianceStatus(java.lang.Integer complianceStatus) {
		this.complianceStatus = complianceStatus;
	}

	public WorkflowItem(java.lang.Long workflowItemId,
			java.lang.String assignedTo, java.lang.String action,
			java.lang.String statusCode, java.lang.Boolean defaultRule,
			java.lang.String role, java.lang.Integer projectId,
			java.lang.Long memberId, java.lang.Long subMeasureGroupId,
			java.lang.String visitSSUI,
			java.util.Date denominatorInclusionDate,
			java.lang.Long medicalRecordId, java.lang.Long chaseItemId,
			java.util.Date dueDate, java.lang.String reviewBy,
			java.util.Date reportingFromDate, java.util.Date reportingToDate,
			java.lang.Boolean activeFlag, java.lang.Long processInstanceId,
			java.lang.String workflowContainerId,
			java.lang.Boolean workflowInProgress,
			java.lang.Integer overreadCount, java.util.Date assignedDate,
			java.util.Date createdDate, java.util.Date modifiedDate,
			java.lang.String createdBy, java.lang.String modifiedBy,
			java.lang.Boolean deletedFlag, java.lang.String projectType,
			java.lang.String workflowItemCode,
			java.lang.String businessGroupCode,
			java.lang.String subMeasureGroupCode,
			java.lang.String workflowIndicator, java.lang.Boolean rtpFlag,
			java.lang.Boolean holdFlag, java.lang.Long workflowRequestId,
			java.lang.String sectionIndicator, java.lang.Boolean exceptionFlag,
			java.lang.Boolean mandatoryReviewFlag,
			java.lang.Long chaseStatusId, java.lang.Boolean editFlag,
			java.lang.Boolean hasMissingValue,
			java.lang.Integer complianceStatus) {
		this.workflowItemId = workflowItemId;
		this.assignedTo = assignedTo;
		this.action = action;
		this.statusCode = statusCode;
		this.defaultRule = defaultRule;
		this.role = role;
		this.projectId = projectId;
		this.memberId = memberId;
		this.subMeasureGroupId = subMeasureGroupId;
		this.visitSSUI = visitSSUI;
		this.denominatorInclusionDate = denominatorInclusionDate;
		this.medicalRecordId = medicalRecordId;
		this.chaseItemId = chaseItemId;
		this.dueDate = dueDate;
		this.reviewBy = reviewBy;
		this.reportingFromDate = reportingFromDate;
		this.reportingToDate = reportingToDate;
		this.activeFlag = activeFlag;
		this.processInstanceId = processInstanceId;
		this.workflowContainerId = workflowContainerId;
		this.workflowInProgress = workflowInProgress;
		this.overreadCount = overreadCount;
		this.assignedDate = assignedDate;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.deletedFlag = deletedFlag;
		this.projectType = projectType;
		this.workflowItemCode = workflowItemCode;
		this.businessGroupCode = businessGroupCode;
		this.subMeasureGroupCode = subMeasureGroupCode;
		this.workflowIndicator = workflowIndicator;
		this.rtpFlag = rtpFlag;
		this.holdFlag = holdFlag;
		this.workflowRequestId = workflowRequestId;
		this.sectionIndicator = sectionIndicator;
		this.exceptionFlag = exceptionFlag;
		this.mandatoryReviewFlag = mandatoryReviewFlag;
		this.chaseStatusId = chaseStatusId;
		this.editFlag = editFlag;
		this.hasMissingValue = hasMissingValue;
		this.complianceStatus = complianceStatus;
	}

}